### ISSUE TITLE
How to compile Mex files?

### ISSUE THREAD

**Issue by leventkaracan** [roimehrez/photorealism#2]
Do we need additional libraries to compile mex files?  When i attempt to compile sGradMex.cpp, ImageReader.h  in Algorithm.h can not be found.

**Comment by roimehrez** [comment]
it can be compiled in **windows** only
you can simple replace it with slower MATLAB implementation
in 'updateImagePoisson.m' replace 
`[dx, dy] = sGradMex(single(origLAB(:,:, c)));`
with 
```
a = single(origLAB(:,:, c));
dx = a - circshift(a,-1,2); 
dy = a - circshift(a,-1,1);
```
